// Generated by CoffeeScript 1.6.3
/* Start File*/


(function() {
  var handle, requestHandlers, router, server;

  server = require("./server");

  router = require('./router');

  requestHandlers = require('./requestHandlers');

  handle = {
    "/": requestHandlers.index,
    "/bootstrap/css/bootstrap.min.css": requestHandlers.css,
    "/image": requestHandlers.image
  };

  server.start(router.route, handle);

}).call(this);
