// Generated by CoffeeScript 1.6.3
/* routeを処理する*/


(function() {
  exports.route = function(handle, pathName, response, request) {
    if (typeof handle[pathName] === 'function') {
      return handle[pathName](response, request);
    } else {
      console.log("No request handler found for " + pathName);
      response.writeHead(404, {
        "Content-Type": "text/plain"
      });
      response.write("404 Not found");
      return response.end();
    }
  };

}).call(this);
