// Generated by CoffeeScript 1.6.3
(function() {
  var http, start, url;

  http = require("http");

  url = require("url");

  start = function(route, handle) {
    var onRequest;
    onRequest = function(request, response) {
      var pathName;
      pathName = url.parse(request.url).pathname;
      console.log("Request received");
      route(handle, pathName, response);
      return response.writeHead(200, {
        "Content-Type": "text/plain"
      });
    };
    http.createServer(onRequest).listen(8888);
    return console.log("Listening on port 3000");
  };

  exports.start = start;

}).call(this);
